title: "JLreq TF meeting YYYY-MM-DD"
body:
  - type: markdown
    attributes:
      value: |
        # How to add new meeting note
        Input area contains a template for meeting notes, including agenda part.
        1. Edit items where appropriate like XXXX-XX-XX for meeting date
        2. Create new discussion from green button
        3. Edit discussion with removing top line starting with `###`
        4. (until meeting) Continue edit discussion with adding agenda items
  - type: textarea
    id: Template
    attributes: 
      label: Template
      description: list agenda items
      value: |
        # JLreq TF meeting YYYY-MM-DD
        - Previous meeting on [YYYY-MM-DD](https://github.com/w3c/jlreq/discussions/XXX)
        - [日本語版 (Japanese edition)]() (終了後、議事録が完成したらリンクが追記されます)
        - Attendee: (to be filled)
        ## Agenda (and notes)
        - GitHub issues
        ## Minutes
        ### The next JLreq TF meeting
        yyyy-mm-dd
